### PR TITLE
Strip DT_PREINIT_ARRAY

### LINKED ISSUE #16: Strip DT_PREINIT_ARRAY for PIE?
https://cs.android.com/android/platform/superproject/+/master:bionic/linker/linker_soinfo.cpp;drc=01be44d2f8aa037bd5e8fcf1d7f04ce4caede3fe;l=535

### PR DESCRIPTION
**Pull request by yujincheng08**
Fix #16

### CODE REVIEW

**Comment by truboxl** [comment]
Suggest to change this to opt-in without checking e_type per my investigation https://github.com/termux/termux-elf-cleaner/issues/16#issuecomment-1531093000

@Grimler91 what do you think?

**Comment by yujincheng08** [comment]
I think it is good. In fact, `e_type` is not accurate for determining PIE. The correct way is to check `DT_FLAGS_1`.

@Grimler91, what do you think?

**Comment by truboxl** [comment]
After reviewing again, I think this is unrelated to PIE.
It is more on to executable vs library and the recommendation to strip DT_PREINIT_ARRAY for executables.
Maybe can check using non-zero `e_entry` vs zero `e_entry`.

**Comment by syphyr** [comment]
I added the following changes to make it opt-in.
https://github.com/syphyr/termux-elf-cleaner/commit/393f32af07f00288e9d7c261ce1d1bff67c73193

**Pull request closed without merging**
